src/routes/Plugin/Common/Rule.js
=> Fix rule plugin handle show style

src/routes/System/AppAuth/index.js, src/routes/System/Dict/index.js, src/routes/System/Metadata/index.js, src/routes/System/Plugin/index.js
=> Add table column resize for Dict,Plugin,Metadata,AppAuth

src/routes/Home/index.js
Issue fixed for bug #184 
Here I have approached by changing the componentDidMount() method. By this approach, the API request will be made only when the user is authenticated.
=> Issue fixed by changing the homepage  componentDidMount()

src/routes/Plugin/Common/Selector.js, src/routes/Plugin/PluginRuleHandle/HystrixRuleHandle.js, src/routes/Plugin/PluginRuleHandle/ParamPluginRuleHandle.js, src/routes/Plugin/PluginRuleHandle/ResponseRuleHandle.js, src/routes/System/AppAuth/TableTransfer.js, src/routes/System/Dict/index.js, src/routes/System/PluginHandle/index.js
about:  https://github.com/apache/incubator-shenyu/issues/3062
fix ： Pagination fails after adding or editing
=> [type:fixbug]fix bug :after add paged is fail

src/layouts/BasicLayout.js, src/routes/Home/home.less, src/routes/Home/index.js, src/services/api.js
about issue https://github.com/apache/incubator-shenyu/issues/3221
=> [type feature ]new home-page

src/routes/System/PluginHandle/index.js
Fixed the bug that when we first entered the PluginHandle page, the PluginName field was incorrectly displayed as 111, and when the Add button was clicked, the PluginName drop-down box was empty.
=> [type:fixbug] fix PluginHandle page data binding bug

src/routes/System/Resource/AddModal.js, src/routes/System/Resource/IconModal.js
Hi, fix some error where meeting in debug mode.  Please reivew thanks.
- fix each child in list should have key in iconModal
- fix received boolean attribute for input placeholder
=> fix each child in list should have key in iconModal

src/routes/Plugin/Common/index.js
=> Added Switch Btn to adjust plugin screen alignment

src/routes/Document/components/AddAndUpdateApiDoc.js
ApiDoc insert update Form field state save exception
=> Fix ApiDoc insert update failure

src/index.ejs
bugfix can not load favicon.ico in dashboard
change warong `favicon.png` to `favicon.ico`
before:
after:
please help to review @yu199195
=> bugfix can not load favicon.ico in dashboard

src/routes/Plugin/Common/Selector.js
=> fix springcloud plugin‘s style display issues

src/components/GlobalHeader/index.js
- bugfix can update state on unmounted component
- update change default password ui 
fix: 
update:
=> bugfix can update state on unmounted component, refactor change default password ui

src/components/GlobalHeader/index.js
- fix password rule that it not think =_+- are special characters
password rule is `Minimum length of 8, including upper and lower case letters, numbers and special characters`
The password eg: `123YSH=abc` `123YSH_abc` `123YSH-abc` `123YSH+abc` can not pass the password rule now due the rule think ` =_+-` are not special characters. 
But the characters `=_+-` are password special characters that we use frequently. User can not find what the problem when them use this characters to change password.     
before: 
after:
=> fix password rule that it not think =_+- are special characters

src/routes/Plugin/Discovery/index.js, src/routes/Plugin/Discovery/tcp.less
This pull request mainly made the following changes:
- fix form style bug
When "npm run build" is executed, some styles are overwritten by antd styles, resulting in loss of styles. Therefore, the styles are re-adjusted to make the styles normal after packaging.
- change the location of the 'id' field
After discussing with the back-end developer, we think it is more appropriate to put the 'id' field in the 'discovery' field. Thus I modified the position of the 'id' field.
=> fix: form style bug

src/routes/Document/components/AddAndUpdateApiDoc.js, src/routes/Document/components/AddAndUpdateTag.js, src/routes/Plugin/Common/Selector.js, src/routes/Plugin/Discovery/TcpCard.js, src/routes/Plugin/Discovery/tcp.less, src/routes/Plugin/PluginRuleHandle/GeneralContextRuleHandle.js, src/routes/System/AppAuth/AddTable.js, src/routes/System/Metadata/AddModal.js
This pr mainly made the following changes：
- fix some code style bugs which cause “npm run lint” to report errors
- change the color of the 'delete' button
- Considering that time is not valuable information, the time on the card is removed, and props and time are displayed in the format of a floating card.
before:
after:
=> Change card

src/routes/Plugin/Common/Rule.js, src/routes/Plugin/Common/Selector.js
It is the frontend support of this backend PR: apache/shenyu#4983  
* When `isBlank` is selected, Value hides & does not judge the value;
* Only [`post`, 'query', 'header', 'cookie'] supports `isBlank`;
=> Support `isBlank`

package.json, src/routes/Document/components/ApiDebug.js
There are several types of responses when API-Debug:  
* JSON  
* TEXT  
* HTML  
-----  
Before:  
> Only JSON is supported  
After:  
> Support all formats of response, JSON with JSON-View, other unified with HTML-View
=> API-Debug page request result exception compatible handling

src/index.less, src/routes/Document/components/SearchApi.js
Before:  
> * The border affects the appearance  
> * Bottom button follows scroll, affecting operation  
After:  
Comparison:
=> Document page left navigation bar style optimization

src/routes/Document/components/ApiDebug.js, src/routes/Document/components/HeadersEditor.js
* HeadersEditor page, which unifies the working data structure into an array, maintains the data order of user operations, and improves the operation experience  
* ApiDebug page, do data conversion, only filtering invalid data at pass to the backend
=> fixed #329

src/index.less, src/locales/en-US.json, src/locales/zh-CN.json, src/routes/System/Plugin/index.js, src/routes/System/Plugin/index.less, src/routes/System/PluginHandle/index.js
=> new feature: quickly add records by copying on the `/config/pluginhandle` page

src/routes/Document/components/ApiInfo.js
https://github.com/apache/shenyu-dashboard/issues/302
before
after
=> when api detail has not requestParameters, use parameters in document

src/routes/Document/components/ApiDebug.js
=> [Bug] fix when not input query,HeadersEditor can not render

package.json, src/layouts/BasicLayout.js, src/layouts/UserLayout.less, src/routes/System/Plugin/index.js
This pr mainly fixes some bugs:
1. In our current code, the state is changed in the render function, thus causing the following warning：
In addition, too much data processing should be avoided in the render function, otherwise performance will be affected. Therefore, I extracted the data processing part of the menus and the calling part of the reducer in the render method as a function.
2. When setting the inline style of an element, change the hyphen naming convention to the camel naming convention.
3. Comment out some redundant code.
=> fix: fix the bug of changing the state during the render process and other small bugs

src/layouts/BasicLayout.js
In my last PR(https://github.com/apache/shenyu-dashboard/pull/335), I extracted the data processing logic of the menu from the render function, which resulted in the locale switching not being reflected in the sidebar in time. This bug is fixed in this PR.
=> fix: fix locale switching bug

src/routes/Document/components/SearchApi.js
Before: 
**Moving the mouse from bottom to top, the upper item will be obscured by the tooltip below, affecting the operation**
After:
**Move the tooltip below to the back so that it does not completely cover the item above**
=> Improving the operational experience of document pages

src/routes/Document/components/ApiDebug.js
=> Fixed the exception of duplicate request headers on the api-debug page

src/routes/System/Alert/index.js
#341 
see: https://legacy.reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data
> The above code is problematic for both server rendering (where the external data won’t be used) and the upcoming async rendering mode (where the request might be initiated multiple times).
> 
> The recommended upgrade path for most use cases is to move data-fetching into componentDidMount
=> [Improve] fetch data at componentDidMount

src/components/Authorized/PromiseRender.js
see: https://github.com/apache/shenyu-dashboard/issues/341
see: https://legacy.reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change
> The recommended upgrade path for this component is to move data updates into componentDidUpdate. You can also use the new getDerivedStateFromProps lifecycle to clear stale data before rendering the new props
=> [Optimization] Optimizing PromiseRender.js Deprecated React Lifecycle

src/utils/AuthRoute.js
related to: https://github.com/apache/shenyu-dashboard/issues/350
In some code development standards, it is not recommended to call asynchronous functions to obtain data in the constructor method, so I solved this bug again.
I found that the problem was that the method of obtaining permissions data was asynchronous. Before the permissions were obtained, the page was rendered empty, which caused an error. Therefore, I added a logic to handle null values on the original code.
=> [fix] fix AuthRoute bug

src/components/CountDown/index.js
issue：https://github.com/apache/shenyu-dashboard/issues/341
1. Moved `initTime` - Now it's a standalone function, not in the class
2. Ditched `componentWillReceiveProps` - Swapped with `getDerivedStateFromProps`
3. Safe State Updates - Added a tiny `setTimeout` in `componentDidUpdate` to manage state changes safely
4. Timer Management - Ensured all timers get cleared when the component says goodbye
5. Clean & Clear - Aimed for code that’s easy to read and understand
All cleaned up and following [React's guidelines](https://fb.me/react-unsafe-component-lifecycles) 🚀👍👀
=> [Optimization] Optimizing CountDown Component Deprecated React Lifecycle

src/utils/AuthRoute.js
I found that the root cause of the error was an incorrect redirection statement in the original code, so I fixed it.
=> fix: fix the bug that caused the plugin list to disappear after refreshing it

src/routes/Plugin/Common/Selector.js, src/routes/Plugin/Discovery/ProxySelectorModal.js, src/routes/Plugin/Discovery/index.js, src/utils/utils.js
This PR mainly made the following changes:
1. Fix selector handler display bug
before:
after:
2. Fix TCP plugin status edit bug
3. Optimize the abandoned life cycle method in the selector component (related to issue https://github.com/apache/shenyu-dashboard/issues/341)
=> [Fix] Fix selector handler display bug

src/routes/Document/ApiDoc.js, src/routes/Document/components/SearchApi.js, src/routes/Document/components/TagInfo.js
1. Upon deleting an API tag, trigger a Popconfirm.
2. When all API tags are removed, refresh the tag information.
=> [Fix] Optimizing api tag delete operation

src/routes/Plugin/Common/CommonRuleHandle.js, src/routes/Plugin/Common/Rule.js
This PR mainly fixes the bug of rule handler display.
before:
after:
=> [Fix] Fix rule handler display bug

src/routes/System/Alert/AddModal.js
- set alert default value. https://github.com/apache/shenyu/issues/5354 
- bugfix matchAll npe
=> [fix] set alert default value, bugfix matchAll npe

src/models/plugin.js, src/routes/System/Plugin/index.js
(related to https://github.com/apache/shenyu-dashboard/issues/381)
The problem with this bug is that the callback function is empty, so I filled the callback body.
=> [fix] Click resource bug

src/routes/Plugin/Common/Rule.js, src/routes/Plugin/Common/index.js
Based on feedback from our community contributor, it was observed that the selector was displaying errors when props were set to null, as depicted in the attached screenshot.
This PR addresses the issue by implementing a fix to handle cases where props are null, ensuring a smoother user experience.
=> [Fix] Fix the selector display bug when the discovery props are null

.github/workflows/deploy.yml, package.json, src/config/config.js, src/routes/User/Login.js, src/services/api.js
https://github.com/apache/shenyu/issues/5255#issue-1962539613
=> Encrypt the password

src/index.less, src/routes/Plugin/Common/index.js, src/routes/Plugin/index.less, src/routes/System/Resource/index.js, src/routes/System/Resource/index.less
**Before:**
***Element is not vertically centered in parent container***
**After:**
***The position in the parent container should not be defined by a specific number, just use the centering attribute of the style system.***
=> Fix exception styles

src/models/resource.js
On the resource management page, click the edit button on the right side of the item on the left tree, and there is no response; trace the reasons because:
```
GET /resource/button?id=XXX
> {"code":500,"message":"密码是默认密码，您必须完成一次更改","data":null}
```
But the page doesn't show the cause of the error.
fixed: When the request is abnormal, the page displays the reason for the exception;
=> Give exception prompt to improve operation experience

src/routes/System/PluginHandle/index.js
The required field itself restricts only 0 and 1, so the default is 0 except for 1, and there are no other possible items;
=> [fixed #382]

src/models/discovery.js
Fixed #438 
Exception should be displayed, not unresponsive
=> Fixed #438

src/router.js, src/routes/Document/ApiDoc.js
Before:
After:
**Previously, the back to top button existed only on document pages, now move it to global**
=> Added global back to top button

src/routes/Plugin/Common/index.js
After the occurrence of Exception #455, the logic will prevent the selector from editing the discovery again because the new record was not successfully added, thus making it impossible to edit.   
Now, the logic is optimized to check if the record exists when saving. If it doesn't exist, it will call the API for adding a new record.
=> Improving the logic when editing the discovery config

.devcontainer/devcontainer.json, .gitpod.yml, README.md
Just like this PR: https://github.com/apache/shenyu/pull/5610, Support `Gitpod` for the frontend project, one-click to start contributing.
=> Support `Contribute with Gitpod`.

src/routes/System/NamespacePlugin/index.js, src/services/api.js, src/utils/namespacePlugin.js
This PR fixes the issue where the plugin edit page could not be opened due to an incorrect query. The request GET /namespacePlugin/id={id}&namespaceId={namespaceId} was using pluginId = {id} for querying, resulting in a failure to retrieve the necessary data. The service method org.apache.shenyu.admin.service.NamespacePluginService#findById has been refactored to findByPluginId, and the frontend has been updated accordingly to use pluginId in the "namespacePlugin/fetchItem" request.
Moreover, the plugin_id field in the plugin_ns_rel table has been updated from a numeric type to VARCHAR(128) to ensure type consistency. Note that bulk operations like delete and enable/disable still use id as the query condition. This PR might be related to the recent changes in the namespace feature. CC: …
=> [type:fix] Correct Plugin ID Query in Namespace Plugin Edit Page

src/routes/System/NamespacePlugin/AddModal.js
=> [type:improve] improve plugin dataType four json form

src/components/GlobalHeader/index.js, src/components/_utils/utils.ts, src/models/global.js, src/routes/System/Namespace/index.js, src/routes/System/User/DataPermModal.js, src/services/api.js
1. remove sessionStorage save namespaceId
2. extract defaultNamespaceId hardcode to util
=> [type:improve] Optimize namespace

src/models/global.js, src/routes/System/NamespacePlugin/index.js, src/services/api.js
fix namespace sync bug
link: https://github.com/apache/shenyu/pull/5765
=> fix namespace sync bug

src/components/GlobalHeader/AddModal.js, src/components/GlobalHeader/index.js, src/locales/en-US.json, src/routes/System/NamespacePlugin/index.js, src/services/api.js
adapt namespce config import export
link: https://github.com/apache/shenyu/pull/5771
=> [type:feature] adapt namespce config import export

src/models/pluginHandle.js, src/routes/Home/index.js, src/routes/Plugin/Common/CommonRuleHandle.js, src/routes/Plugin/Common/ComposeRuleHandle.js, src/routes/Plugin/Common/Rule.js, src/routes/Plugin/PluginRuleHandle/index.js
=> [type:improve] support custom rule handle with plugin handler config

src/components/GlobalHeader/index.less
Font size is too large, causing display issues in some browsers
[https://github.com/apache/shenyu-dashboard/issues/519](https://github.com/apache/shenyu-dashboard/issues/519)
=> [fix]Font size is too large, causing display issues in some browsers

src/routes/Plugin/Discovery/DiscoveryUpstreamTable.js
Replaces hardcoded status options with localized content using `getIntlContent` for better internationalization.
Adjusts initial value handling for form fields and refines status rendering logic to ensure consistency.
Improves maintainability and prepares the application for multi-language support.
=> fix divide plugin: localizes status labels.
