src/routes/plug/common/index.js
src/routes/plug/divide/index.js
src/routes/plug/dubbo/index.js
src/routes/plug/limiter/index.js
src/routes/plug/monitor/index.js
src/routes/plug/rewrite/index.js
src/routes/plug/sign/index.js
src/routes/plug/spring/index.js
src/routes/plug/waf/index.js

fix pagination defects

---

src/routes/plug/hystrix/Rule.js
src/routes/plug/hystrix/index.js

hystrix 插件支持配置 线程池隔离模式 
hystrix 插件 支持配置降级处理

hystrix 插件增加 线程池模式以及callBackUri

---

.github/workflows/build.yml
.stylelintrc.json
src/components/Login/LoginTab.js
src/models/auth.js
src/models/pluginHandle.js
src/routes/plug/common/Rule.js
src/routes/plug/divide/index.js
src/routes/plug/dubbo/Selector.js
src/routes/plug/hystrix/Rule.js
src/routes/plug/hystrix/Selector.js
src/routes/plug/limiter/Rule.js
src/routes/plug/limiter/Selector.js
src/routes/plug/monitor/Rule.js
src/routes/plug/monitor/Selector.js
src/routes/plug/rewrite/Rule.js
src/routes/plug/rewrite/Selector.js
src/routes/plug/sign/Selector.js
src/routes/plug/spring/Rule.js
src/routes/plug/spring/Selector.js
src/routes/sysytem/appAuth/AddModal.js
src/routes/sysytem/appAuth/TableTransfer.js
src/routes/sysytem/appAuth/index.js
src/routes/sysytem/metadata/AddModal.js
src/services/api.js

closes [https://github.com/dromara/soul-dashboard/issues/16](https://github.com/dromara/soul-dashboard/issues/16)

Fix eslint and add `npm run lint` to build action

---

src/common/menu.js
src/common/router.js
src/models/soulDict.js
src/routes/plug/common/Rule.js
src/routes/sysytem/dict/AddModal.js
src/routes/sysytem/dict/index.js
src/routes/sysytem/plugin/AddPluginHandle.js
src/routes/sysytem/plugin/PluginHandle.js
src/services/api.js

for [https://github.com/dromara/soul/issues/349](https://github.com/dromara/soul/issues/349)

Optimize the plugin handle

---

src/routes/System/AppAuth/AddTable.js

The Selector can input and cell in table can input.

Optimize the authentication management page.

---

src/components/SiderMenu/SiderMenu.js

fixes [https://github.com/dromara/soul-dashboard/issues/28](https://github.com/dromara/soul-dashboard/issues/28)

Fix menu select bug

---

src/services/api.js

frontend refactor for soul #402

refactor soul #402

---

src/routes/System/Plugin/AddModal.js

Remove required rule for plugin config field

---

src/components/GlobalFooter/index.js
src/routes/Plugin/Divide/Selector.js

wait for [https://github.com/dromara/soul/pull/497](https://github.com/dromara/soul/pull/497)

Add divide service warmup field config

---

src/locales/en-US.json

Use Enable replace Disabled.

---

src/routes/System/PluginHandle/index.js

fix #68 PluginHandler Delete Button Display

---

src/routes/System/Dict/index.js
src/routes/System/Metadata/index.js
src/routes/System/Plugin/index.js
src/utils/AuthButton.js
src/utils/AuthRoute.js
src/utils/utils.js

Fiexd the bug that paging query does not work after click [System Manage/Plugin/Batch Enable Or Disabled] button and optimize some translation. (#70)

Fiexd the bug that paging query does not work after click  Batch Enable Or Disabled... (#70)

---

src/locales/zh-CN.json
src/routes/System/AppAuth/AddTable.js

delete required in appParam and extendInfo, modify translation for phone

---

src/routes/Plugin/Common/index.js
src/routes/System/AppAuth/index.js
src/routes/System/Dict/index.js
src/routes/System/Metadata/index.js
src/routes/System/Plugin/index.js
src/routes/System/PluginHandle/index.js
src/routes/System/Resource/index.js
src/routes/System/Role/index.js
src/routes/System/User/index.js

Adjust the table column's width  and add sorter to some column.

---

src/routes/System/Metadata/AddModal.js

Some fields in the metadata are set to not be required

Some fields in the metadata are set to not be required

---

src/routes/System/PluginHandle/AddModal.js

in divide selector handler , protocol not Required

Required sets the default value to no and is not required

---

src/routes/Plugin/PluginRuleHandle/ResponseRuleHandle.js
src/routes/Plugin/PluginRuleHandle/index.js

Support response plugin (#131)

---

src/models/shenyuDict.js

Fix the bug when we operate as follow:
1、Update the dic item.
2、Click modify in the rulesList of divide plugin.
The error exist in the console.

Fix dictionary

---

src/routes/Plugin/Common/Selector.js

fix#2278 , A new pull request,please check it,thanks!

---

src/layouts/BasicLayout.js

Optimise the basic layout while the interface '/plugin' need authority.

Optimise the basic layout

---

src/routes/System/Plugin/AddModal.js

[ISSUE #159] Fix the plugin sort can not support bigger than 100

---

src/routes/System/AppAuth/index.js

fix TableTransferComponent : modify data error.

fix tableTransferComponent : modify data error.

---

src/routes/System/AppAuth/AddModal.js
src/routes/System/AppAuth/AddTable.js

i fix some paging bugs in the addition and modification of the AppAuth.

FIX some paging bugs in the addition and modification of the AppAuth.

---

src/routes/System/PluginHandle/index.js

about issue #190 
Reset page number after condition changed 
pluginHandle/index

[ISSUE #190] Reset page number after condition changed  [plugin handle]

---

src/routes/System/Plugin/index.js
src/routes/System/PluginHandle/index.js

about issue #190
work list:
eg:
before:
after:

[type:feature]fix page error[plugin]/new theme

---

src/assets/background.svg
src/layouts/UserLayout.less

fix login background  images can not  be  loaded without network. 
https://github.com/apache/incubator-shenyu/issues/3194

fix shenyu admin  login background  images can not  be  loaded without network.

---

src/routes/System/AppAuth/SearchContent.js
src/routes/System/AppAuth/index.js
src/routes/System/Dict/index.js
src/routes/System/Metadata/index.js

about issue https://github.com/apache/incubator-shenyu-dashboard/issues/190
Reset page number after condition changed
- metadata/index
- appauth/index
- dict/index

[ISSUE #190] Reset page number after condition changed [metadata/appauth/dict]

---

src/index.ejs
src/routes/System/Metadata/AddModal.js
src/routes/System/Metadata/index.js

fix:bug metadata edit error

---

src/routes/System/AppAuth/AddModal.js

[ISSUE #]fixbug/app-atuh-edit-error

---

src/routes/System/Plugin/index.js

fix warning error in console about fontWeight

[type:fixbug] fix warning error in console about fontWeight

---

src/layouts/BasicLayout.js

fix warning error in console about componentWillUnmount method

[type:fixbug] fix warning error in console about componentWillUnmount method

---

src/locales/en-US.json
src/locales/zh-CN.json
src/routes/System/Metadata/index.js
src/services/api.js

Hi community: 
I have completed the feature use path to search.
please review the code.
see issues [use path to search](https://github.com/apache/incubator-shenyu/issues/3631)

feature: use path to search

---

src/routes/System/AppAuth/index.js
src/routes/System/Dict/index.js
src/routes/System/Metadata/index.js
src/routes/System/Plugin/index.js
src/routes/System/PluginHandle/index.js

Hi, community
I have finished pagination can chose pageSize basicConfig module
see Issues [ISSUE #216](https://github.com/apache/incubator-shenyu-dashboard/issues/216)
please review code.

[ISSUE #216] pagination can chose pageSize

---

src/routes/System/PluginHandle/index.js

Fixes [https://github.com/apache/shenyu-dashboard/issues/223](https://github.com/apache/shenyu-dashboard/issues/223)

Fix pluginDropDownList

---

package.json

Solve the problem of not being able to npm install
Fixes https://github.com/apache/shenyu-dashboard/issues/194
Fixes https://github.com/apache/shenyu-dashboard/issues/226

Solve the problem of not being able to npm install

---

src/routes/System/PluginHandle/index.js

[type feature] handle-index optimization

---

src/routes/System/Dict/index.js
src/routes/System/PluginHandle/index.js

dict-index page optimization 
eg:

[type:feature] dict-index optimization 

---

src/routes/System/Dict/AddModal.js
src/routes/System/Metadata/AddModal.js

[type: fixbug]fixbug/add-model-edit-fail

---

src/routes/Home/index.js

update  value=""    throw Uncaught SyntaxError: Unexpected token ')'

Unable to meet conditions  ""

---

src/models/plugin.js
src/routes/System/Plugin/index.js

https://github.com/apache/shenyu-dashboard/issues/251

add "enabled" param in plugin's reload action#4172

---

.github/workflows/build.yml
src/routes/System/Plugin/AddModal.js

Fixes [https://github.com/apache/shenyu/issues/4211](https://github.com/apache/shenyu/issues/4211)

Fixed naming conflicts between plugin attributes and plugin config attributes

---

src/components/SiderMenu/SiderMenu.js
src/routes/System/Plugin/index.js

closes [https://github.com/apache/shenyu/issues/4174](https://github.com/apache/shenyu/issues/4174)

Add link from plugin to pluginList

---

src/components/SiderMenu/SiderMenu.js
src/routes/System/Plugin/index.js

Reverts apache/shenyu-dashboard#255
Now the menu click is not responsive.

Revert "Add link from plugin to pluginList"

---

src/routes/Plugin/Common/index.js

插件列表里的选择器和规则新增执行顺序列，便于根据权重了解执行顺序，同时后端sql追加排序，按执行顺序从小到大排序后返回前端

[enhancement]: selectors and rules order by execution 

---

src/components/SiderMenu/SiderMenu.js
src/layouts/BasicLayout.js

> Now, although the user can add a menu to the resource, the menu other than the plugin will not be dynamically loaded and displayed.
This pr provide a feature to support user custom dynamic menu. Also can custom extern link menu.
Hi guys, I'm not familiar with react, please review and give the advice!.

feat: support custom dynamic menu

---

src/routes/Plugin/Common/Selector.js

fix issue #306

---

src/routes/Document/components/SearchApi.js

[BUG] Document page will occur error when no doc node

---

src/components/GlobalHeader/index.js
src/components/GlobalHeader/index.less

New help entry, convenient for users to seek support

---

src/index.less
src/locales/en-US.json
src/locales/zh-CN.json
src/routes/System/Metadata/index.js
src/routes/System/Plugin/index.js
src/routes/System/Plugin/index.less
src/routes/System/PluginHandle/index.js

see: https://github.com/apache/shenyu-dashboard/pull/324#issuecomment-1687307049

new feature: quickly add records by copying on the `/config/metadata` page

---

src/index.less
src/locales/en-US.json
src/locales/zh-CN.json
src/routes/System/Dict/index.js
src/routes/System/Plugin/index.js
src/routes/System/Plugin/index.less
src/routes/System/PluginHandle/index.js

see: https://github.com/apache/shenyu-dashboard/pull/324#issuecomment-1687307049

new feature: quickly add records by copying on the `/config/dict`

---

src/routes/Document/components/ApiDebug.js

fixed #327

---

src/components/Login/map.js

Add a quick clear button to all Input components in login page

---

src/routes/System/Alert/AddModal.js
src/routes/System/Alert/index.js
src/services/api.js

close: https://github.com/apache/shenyu-dashboard/issues/345

[Optimization] Some optimization points for the Alert module

---

src/routes/System/Resource/index.js

see: https://github.com/apache/shenyu-dashboard/issues/341

[Optimization] Optimizing Deprecated React Lifecycle

---

src/utils/AuthRoute.js

see https://github.com/apache/shenyu-dashboard/issues/341

[Optimization] Optimizing AuthRoute.js Deprecated React Lifecycle

---

src/utils/AuthRoute.js

close：https://github.com/apache/shenyu-dashboard/issues/350

[Fix] Fix Proxy page error cause componentDidMount

---

src/components/Login/LoginTab.js

see https://github.com/apache/shenyu-dashboard/issues/341

[Optimization] Optimizing LoginTab.js Deprecated React Lifecycle

---

src/components/SiderMenu/SiderMenu.js

see https://github.com/apache/shenyu-dashboard/issues/341

[Optimization] Optimizing SiderMenu.js Deprecated React Lifecycle

---

src/routes/Plugin/Common/Rule.js

see https://github.com/apache/shenyu-dashboard/issues/341

[Optimization] Optimizing Rule.js Deprecated React Lifecycle

---

src/routes/System/Dict/index.js

[fixed #370] Unify the Popover of `/config/dict`

---

src/routes/Document/components/AddAndUpdateApiDoc.js
src/routes/Document/components/SearchApi.js

close: https://github.com/apache/shenyu-dashboard/issues/296
for now:
The interaction design of the pop-up window will be modified in subsequent updates.

[Optimization] Optimizing JSON writing experience

---

src/routes/System/Alert/AddModal.js

[Fix] fix alert add/update modal tag delete problem

---

src/services/api.js

Backend pr https://github.com/apache/shenyu/pull/5342

[type:refactor] fix upload bug

---

src/routes/System/Alert/AddModal.js
src/services/api.js

Fix upload plugin

---

src/routes/Plugin/Common/CommonRuleHandle.js
src/routes/Plugin/Common/Rule.js
src/routes/Plugin/Common/Selector.js
src/routes/Plugin/Discovery/ProxySelectorModal.js
src/utils/utils.js

related to https://github.com/apache/shenyu/issues/5343

[Fix] Fix select option display bug and form validation bug

---

src/routes/System/Dict/index.js

related to https://github.com/apache/shenyu/issues/5373

Fix admin: show the dictCode

---

src/routes/Home/home.less
src/routes/Home/index.js

Optimize the visual experience of the home event list

---

src/routes/Plugin/Common/Rule.js

Fixed null pointer exception on copy rule page

---

src/routes/System/Role/AddModal.js

[fixed #192]

---

src/models/shenyuDict.js

Clear the current list before refreshing the list data to avoid contaminating the list

fixed #404

---

src/index.less

Optimize shown style in popover component 

---

src/models/auth.js
src/models/metadata.js

Supplement unified operation message

---

src/index.less

Optimize table styles

---

.webpackrc.js

https://github.com/apache/shenyu/issues/3257

[Fix] Resolve dashboard routing mismatch post context-path update

---

src/components/GlobalHeader/index.js

Add permission controls to import & export

---

src/index.ejs
src/services/api.js

The improvement of #428

---

src/routes/System/AppAuth/index.js
src/routes/System/Dict/index.js
src/routes/System/Metadata/index.js
src/routes/System/Plugin/index.js
src/routes/System/User/index.js
src/utils/AuthButton.js

`AuthButton` component adds support for configuring alternative content without permission.
eg:
without permission:
with permission:

Enhanced AuthButton component

---

src/components/Login/map.js

Added support for displaying passwords

---

src/routes/Plugin/Common/Selector.js
src/routes/Plugin/index.less

Before:
①: Inconsistent spacing between input and button
②: The line-height of the input and button are inconsistent
③: Button group layout unreasonable
After:

Optimize the conditions layout of the selector form

---

src/routes/Plugin/Common/Rule.js

Optimize the conditions layout of the rule form

---

src/routes/System/User/AddModal.js

Optimize the layout of [Add User] form

---

src/routes/Plugin/Common/index.js

Before:
After:
**Make full use of space, adjust the input box width limit to the min-width limit;**

Optimize the selector search box layout of the plug page

---

src/routes/System/Resource/index.js

Optimize the menu-list search box layout of the resource page

---

src/routes/Plugin/Common/Selector.js
src/routes/Plugin/index.less

Optimize the layout of springCloud/selector/form

---

src/routes/Plugin/Common/CommonRuleHandle.js
src/routes/Plugin/index.less

Optimize the handler layout of the rule form

---

src/routes/Plugin/Common/Selector.js
src/routes/Plugin/index.less

Optimize the handler layout of the selector form

---

src/routes/Plugin/PluginRuleHandle/HystrixRuleHandle.js

Optimize the layout of HystrixRuleHandle

---

src/routes/Plugin/PluginRuleHandle/RequestRuleHandle.js

Optimize the layout of RequestRuleHandle

---

src/routes/Plugin/PluginRuleHandle/GeneralContextRuleHandle.js

Optimize the layout of GeneralContextRuleHandle

---

src/routes/Plugin/Common/Selector.js

fixed #455

---

src/routes/System/User/index.js

[Improve] admin not show edit

---

src/components/GlobalHeader/index.js

Optimize the layout of the top "Namespace"

---

src/models/login.js
src/routes/System/User/index.js
src/routes/User/Login.js

[Improve] need verify code when password error

---

src/routes/User/Login.js

Link: https://github.com/apache/shenyu/pull/5600
Please merge [this PR](https://github.com/apache/shenyu-dashboard/pull/465) first.

[Feature] Invalidate Previous Tokens on New Login by Implementing Client ID Validation

---

src/models/common.js
src/routes/Plugin/Common/RuleCopy.js
src/routes/Plugin/Common/SelectorCopy.js
src/routes/Plugin/Common/index.js
src/services/api.js

link: https://github.com/apache/shenyu-dashboard/issues/469

[Improve] Selector module adaptation namespace

---

src/components/GlobalHeader/index.js
src/models/global.js
src/models/login.js

[type:fix] fetch namespace problem when not login

---

src/models/common.js
src/models/metadata.js
src/routes/Plugin/Common/Rule.js
src/routes/Plugin/Common/RuleCopy.js
src/routes/Plugin/Common/index.js
src/routes/System/Metadata/index.js
src/services/api.js

[Improve] Rule and MetaData module adaptation namespace

---

src/routes/System/Namespace/index.js
src/routes/System/User/index.js

[Improve] Disable unnecessary operator row checkboxes

---

src/services/api.js

Fix pathvariable

---

src/models/auth.js
src/routes/System/AppAuth/AddModal.js
src/routes/System/AppAuth/index.js
src/services/api.js

link: #469
see gif, please wait load:

[type:feat] auth module support namespace

---

src/components/GlobalHeader/index.js
src/routes/System/User/DataPermModal.js

link：#469
1. hidden namespace select component some page
2. data permission config modal support namespace

[Improve] Rule and MetaData module adaptation namespace 

---

src/routes/System/NamespacePlugin/index.js
src/services/api.js
src/utils/namespacePlugin.js

fontend part of: 
https://github.com/apache/shenyu/pull/5668
see gif:

[type:fix] fix namespace url error

---

src/routes/Plugin/Common/index.js
src/routes/Plugin/Discovery/DiscoveryImportModal.js
src/routes/Plugin/Discovery/ProxySelectorCopy.js
src/routes/Plugin/Discovery/index.js

[type:feat] discovery module adaptation namespace

---

src/components/GlobalHeader/index.js
src/models/global.js
src/services/api.js

change current namespace, then refresh plugin menu list
link: https://github.com/apache/shenyu/pull/5746

[type:feat] support filter permissions by namespace

---

src/models/global.js

[type:fix] fix call getUserPermissionByToken without token when startup

[type:fix] fix call getUserPermissionByToken without token when startup

---

src/routes/System/NamespacePlugin/index.js

remove 'resource' button in namespacePlugin

remove 'resource' button in namespacePlugin

---

src/services/api.js
src/utils/AuthRoute.js

[type:fix] fix can not Modify Selector MetaData Rule

[type:fix] fix can not Modify Selector MetaData Rule

---

src/services/api.js

[type:fix] remove an additional delimiter on find meta-data url path

---

src/routes/Plugin/Common/RuleCopy.js
src/routes/Plugin/Common/SelectorCopy.js
src/services/api.js

link: https://github.com/apache/shenyu/pull/5787

selector copy and rule copy adapted to namespace

---

src/models/namespacePlugin.js
src/routes/Plugin/Common/index.js
src/routes/System/Plugin/index.js
src/services/api.js
src/utils/namespacePlugin.js

plugin enabled adapted namespace
link: https://github.com/apache/shenyu/pull/5790

plugin enabled adapted namespace

---

src/components/GlobalHeader/ExportModal.js
src/components/GlobalHeader/ImportModal.js
src/components/GlobalHeader/index.js
src/models/global.js
src/models/login.js
src/routes/Home/index.js
src/services/api.js

fix namespace bugs
link: https://github.com/apache/shenyu/pull/5799

fix namespace bugs

---

src/models/namespacePlugin.js
src/routes/Home/index.js
src/routes/Plugin/Common/SelectorCopy.js
src/routes/System/NamespacePlugin/index.js
src/services/api.js
src/utils/namespacePlugin.js

[bugfix] fix namespace bugs 20241127
link: https://github.com/apache/shenyu/pull/5823

[bugfix] fix namespace bugs 20241127

---

src/models/global.js
src/routes/Plugin/Common/RuleCopy.js
src/routes/Plugin/Common/SelectorCopy.js
src/routes/Plugin/Common/index.js
src/routes/System/Alert/index.js
src/routes/System/NamespacePlugin/index.js
src/routes/System/User/DataPermModal.js
src/services/api.js

link: https://github.com/apache/shenyu/pull/5823

[Bugfix] namespace plugin batch enable

---

src/models/global.js
src/routes/Plugin/Common/index.js

fix ns plugin sync bug
link : https://github.com/apache/shenyu/pull/5847

fix ns sync bug

---

src/routes/Plugin/Common/index.js

fix update plugin

---

src/routes/System/NamespacePlugin/index.js
src/routes/System/Plugin/index.js

fix https://github.com/apache/shenyu/issues/5937

[fix] not set page to 1 after close plugin edit dailog box

---

src/routes/Document/components/ApiInfo.js

Front end for
https://github.com/apache/shenyu/issues/5940
https://github.com/apache/shenyu/pull/5946

support get response type from document json

---

.gitpod.Dockerfile
.gitpod.yml

Optimize the Gitpod configuration, making the development environment independent of the Gitpod file, which facilitates later customization and maintenance.

Configuring gitpod with java

---

src/components/SiderMenu/SiderMenu.js

close https://github.com/apache/shenyu/issues/6063

[type:fix] sider menu support resize

---

src/routes/Plugin/McpServer/index.js

fix mcpserver delete error. #542

[fix] mcpserver delete error

---

src/routes/Plugin/McpServer/index.js

fix: mcpServer blank page issue. #544

[fix] mcpServer blank page issue
